- name: Setup all the required packages/softwares to run an Angular application
  hosts: my_instances
  become: true
  tasks:
    - name: Update APT package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install nodejs
      ansible.builtin.apt:
        name: nodejs
        state: present

    - name: Install npm
      ansible.builtin.apt:
        name: npm
        state: present

    - name: Install Angular CLI
      ansible.builtin.npm:
        name: '@angular/cli'
        global: yes
        state: present
